- hosts: neutron_servers
  gather_facts: False
  remote_user: root
  tasks:
    - import_tasks: ./basic/test.yml
      tags: basic
      run_once: True
    
    - import_tasks: ./tls/test.yml
      tags: tls
      run_once: True
    
    - import_tasks: ./tcphttps/test.yml
      tags: tcphttps
      run_once: True

    - import_tasks: ./persist/test.yml
      tags: persist
      run_once: True

    - import_tasks: ./l7x/test.yml
      tags: l7x
      run_once: True

    - import_tasks: ./customized/test.yml
      tags: customized
      run_once: True

    - import_tasks: ./ftp/test.yml
      tags: ftp
      run_once: True

    - import_tasks: ./udp/test.yml
      tags: udp
      run_once: True

    - import_tasks: ./bwc/test.yml
      tags: bwc
      run_once: True

    - import_tasks: ./ipv6/test.yml
      tags: ipv6
      run_once: True
      when: test_env == 'osp'