---

- hosts: bigips
  gather_facts: False
  remote_user: root
  tasks:
    - name: check bigips be reachable
      ping:
      
    - name: collect bigip partitions
      bigip_device_info:
        gather_subset:
          - partitions
          - self-ips
          - vlans
        provider:
          user: admin
          server: "{{ inventory_hostname }}"
          password: "{{ admin_password }}"
          validate_certs: False
      register: bigip_infos
      tags: getbigipinfo

    - name: show all partitions
      debug: var=bigip_infos
      tags: getbigipinfo

    - name: remove objects under partitions
      file: path=/config/partitions/{{ item.name }} state=absent
      with_items: "{{bigip_infos.partitions}}"
      when: item.name != 'Common'
    
    - name: executing tmsh load sys config
      shell: tmsh load sys config

    - name: delete partitions
      bigip_partition:
        name: "{{item.name}}"
        state: absent
        provider:
          user: admin
          server: "{{ inventory_hostname }}"
          password: "{{ admin_password }}"
          validate_certs: False
      with_items: "{{bigip_infos.partitions}}"
      when: item.name != "Common"
    
    - name: delete self-ips
      bigip_selfip:
        name: "{{ item.name }}"
        state: absent
        provider:
          user: admin
          server: "{{ inventory_hostname }}"
          password: "{{ admin_password }}"
          validate_certs: False
      with_items: "{{ bigip_infos.self_ips }}"
      when: item.full_path != '/Common/vtep' and (item.name | regex_search('^.*[0-9a-f\-]{36}$'))

    - name: delete vlans
      bigip_vlan:
        name: "{{ item.name }}"
        state: absent
        provider:
          user: admin
          server: "{{ inventory_hostname }}"
          password: "{{ admin_password }}"
          validate_certs: False
      with_items: "{{ bigip_infos.vlans }}"
      when: (item.description | default('') | regex_search('^[0-9a-f\-]{36}$'))
