---

- hosts: neutron_servers
  gather_facts: False
  remote_user: root
  tasks:
    - import_tasks: ./task-download-scripts.yml
      run_once: True
      
    - include_tasks: "../testcases/{{testname.name}}/test.yml"
      with_items: "{{ testcases }}"
      loop_control: 
        loop_var: testname
      run_once: True
