# TODO: setup client and backend servers.
#   Refer to: https://github.com/zongzw-learn/learn-consul/blob/main/setup-examples/0.setup-server.yml

---

- hosts: clients
  gather_facts: false
  remote_user: root
  tasks:
    - import_tasks: ./task-set-webproxy.yml
      when: webproxy is defined
      run_once: true

    - name: check clients are reachable
      ping:
      delegate_to: localhost

    - name: update /etc/resolv.conf
      template:
        src: ../conf.d/templates/resolv.conf.j2
        dest: /etc/resolv.conf

    - name: make sure yum packages installed
      yum:
        name: 
          - wget
          - curl
          - vim
      environment: "{{ proxy_env | default({}) }}"

    - import_tasks: ./task-download-scripts.yml
