- name: set timestamp variable
  shell: echo $$-`date +%s`
  register: test_timestamp
  delegate_to: localhost

- name: set neutron resource names
  set_fact:
    testcasename: "{{ test_casename | default('Common-Test') }}"

    subnet: "{{ test_subnet }}"
    loadbalancer: lb-{{ test_timestamp.stdout }}
    listener: ls-{{ test_timestamp.stdout }}
    pool: pl-{{ test_timestamp.stdout }}
    member: mb-{{ test_timestamp.stdout }}
    l7policy: l7-{{ test_timestamp.stdout }}
    healthmonitor: hm-{{ test_timestamp.stdout }}

    loadbalancer_additional_options: "{{ test_loadbalancer_additional_options | default('') }}"
    pool_protocol: "{{ test_pool_protocol | default('HTTP') }}"
    listener_protocol: "{{ test_listener_protocol | default('HTTP')}}"
    listener_tcpport: "{{ test_listener_tcpport | default(80) }}"
    listener_additional_options: "{{ test_listener_additional_options | default('') }}"
    member_tcpport: "{{ test_member_tcpport | default(80) }}"
    healthmonitor_protocol: "{{ test_healthmonitor_protocol | default('PING') }}"
