- set_fact:
    test_casename: smoking test
    test_listener_protocol: HTTP
    test_pool_protocol: HTTP
    test_listener_tcpport: 80
    tenant_name: smokingtest
    
- import_tasks: ./task-define-resources.yml

- import_tasks: ./task-create-resources.yml

- import_tasks: ./task-get-resourceids.yml

- import_tasks: ./task-check-resources-created.yml

- import_tasks: ./task-remove-resources.yml

- import_tasks: ./task-check-resources-removed.yml
