- name: collect bigip device info
  bigip_device_info:
    gather_subset:
      # - system-info
      - partitions
      # - provision-info
      # - interfaces
      # - client-ssl-profiles
      - ltm-pools
      - virtual-servers
      # - vlans
      # - nodes
      - virtual-addresses
      # - profiles
      # - devices
      # - http-profiles
      - "{{ monitor_type }}"
    provider:
      user: admin
      server: "{{ item }}"
      password: "{{ hostvars[item].admin_password }}"
      validate_certs: False
  register: bigip_infos
  with_items: "{{ groups['bigips'] }}"
  delegate_to: localhost
  when: nodelete is not defined

- name: assert resources are removed on bigips
  assert:
    that:
      - "'{{project_id}}' not in '{{item.partitions | map(attribute='name') | list | join(' ') }}'"
      - "'{{loadbalancer_id}}' not in '{{item.virtual_addresses | map(attribute='name') | list | join(' ') }}'"
      - "'{{listener_id}}' not in '{{item.virtual_servers | map(attribute='name') | list | join(' ') }}'"
      - "'{{pool_id}}' not in '{{item.ltm_pools | map(attribute='name') | list | join(' ') }}'"
      - "'{{ healthmonitor_id }}' not in '{{ item[monitor_type_result] | map(attribute='name') | list | join(' ') }}'"
    quiet: yes
  with_items: "{{bigip_infos.results}}"
  loop_control:
    label: "{{ item.item }}"
  when: nodelete is not defined

- name: assert members are removed on bigips
  assert:
    that:     
      - "'{{ item[0] }}' not in '{{ item[1].ltm_pools | map(attribute='members',default=' ') | flatten | map(attribute='description',default=' ') | list | join(' ') }}'"
    quiet: yes
  with_nested:
    - "{{ member_ids }}"
    - "{{ bigip_infos.results }}"
  loop_control:
    label: "memberid: '{{ item[0] }}'"
  when: nodelete is not defined
