---

- name: list the files of patches directory
  shell: ls chdir=../patches
  register: patch_files
  delegate_to: localhost
  tags: copyfile
  run_once: True

# TODO: check if there is new code change in pipeline.
- name: customize neutron* code
  copy: src=../patches/{{ item }} dest=/ force=yes
  with_items: "{{ patch_files.stdout_lines }}"
  tags: copyfile

- import_tasks: ./task-neutron-db-info.yml
  tags: migratedb

- name: migrate neutron db tables
  mysql_db:
    name: "{{neutron_db_info.results[3].stdout}}"
    login_user: "{{neutron_db_info.results[0].stdout}}"
    login_password: "{{neutron_db_info.results[1].stdout}}"
    login_host: "{{neutron_db_info.results[2].stdout}}"
    target: /tmp/scripts/customizing.db.sql
    state: import
  run_once: True
  tags: migratedb