- name: set timestamp variable
  shell: echo $$-`date +%s`
  register: test_timestamp
  delegate_to: localhost

- name: set neutron resource names
  set_fact:
    testcasename: "{{ test_casename | default('Common-Test') }}"

    subnet: "{{ test_subnet }}"
    loadbalancer: lb-{{ test_timestamp.stdout }}
    listener: ls-{{ test_timestamp.stdout }}
    pool: pl-{{ test_timestamp.stdout }}
    member: mb-{{ test_timestamp.stdout }}
    l7policy: l7-{{ test_timestamp.stdout }}
    healthmonitor: hm-{{ test_timestamp.stdout }}

    loadbalancer_additional_options: "{{ test_loadbalancer_additional_options | default('') }}"
    pool_protocol: "{{ test_pool_protocol | default('HTTP') }}"
    listener_protocol: "{{ test_listener_protocol | default('HTTP')}}"
    listener_tcpport: "{{ test_listener_tcpport | default(80) }}"
    listener_additional_options: "{{ test_listener_additional_options | default('') }}"
    member_tcpport: "{{ test_member_tcpport | default(80) }}"
    healthmonitor_protocol: "{{ test_healthmonitor_protocol | default('PING') }}"

- set_fact:
    monitor_type: gateway-icmp-monitors
    monitor_type_result: gateway_icmp_monitors
  when: healthmonitor_protocol == 'PING'

- set_fact:
    monitor_type: tcp-monitors
    monitor_type_result: tcp_monitors
  when: healthmonitor_protocol == 'TCP'

- set_fact:
    monitor_type: http-monitors
    monitor_type_result: http_monitors
  when: healthmonitor_protocol == 'HTTP'

- set_fact:
    monitor_type: https-monitors
    monitor_type_result: https_monitors
  when: healthmonitor_protocol == 'HTTPS'

- set_fact:
    loadbalancer_additional_options: --bandwidth 200 {{ loadbalancer_additional_options }}
  when: (versions.lbaas | string != 'oss') and not (loadbalancer_additional_options | regex_search('--bandwidth'))

- set_fact:
    tenant: "{{ tenant_name }}-{{ test_timestamp.stdout }}"
  when: tenant_name is defined