- name: "{{ testcasename }}: remove one member from pool"
  shell: |
    source {{ openrc }} && \
    bash /tmp/scripts/wait_assert_lb_active.sh {{ loadbalancer }} && \
    neutron lbaas-member-delete {{ member_ids[0] }} {{ pool }}
  when: nodelete is not defined

- name: "{{ testcasename }}: delete lbaasv2 resources"
  shell: |
    source {{ openrc }} && bash /tmp/scripts/wait_assert_lb_active.sh {{ loadbalancer }} && {{ item }}
  with_items:
    - neutron lbaas-healthmonitor-delete {{ healthmonitor }}
    - neutron lbaas-pool-delete {{ pool }}
    - neutron lbaas-listener-delete {{ listener }}
    - neutron lbaas-loadbalancer-delete {{ loadbalancer }}
  when: nodelete is not defined

- name: pause for 15 seconds to wait for loadbalancer on bigip disappears
  pause: seconds=15
  when: nodelete is not defined

- import_tasks: ./task-remove-testcase-tenant.yml
  when: tenant is defined and nodelete is not defined