
- name: download f5-* packages
  get_url: url={{ item }} dest=/tmp timeout=30
  with_items:
    - "{{ download_prefix }}/f5-sdk-{{ versions.f5sdk }}-1.el7.noarch.rpm"
    - "{{ download_prefix }}/f5-icontrol-rest-{{ versions.icontrol }}-1.el7.noarch.rpm"
    - "{{ download_prefix }}/f5-openstack-lbaasv2-driver-{{ versions.driver }}-1.el7.noarch.rpm"
    - "{{ download_prefix }}/f5-openstack-agent-{{ versions.agent }}-1.el7.noarch.rpm"
  when: (download_prefix | regex_search("^https://github.com")) == None

# TODO: remove the github sceniaro, and support build release test, like: f5-openstack-agent-9.9.2-338.el7.noarch.rpm
#    this rpm name format is different with f5-openstack-agent-9.8.45-1.el7.noarch.rpm, where build number is not 1
- name: download f5-* packages
  get_url: url={{ item }} dest=/tmp timeout=30
  with_items:
    - https://github.com/F5Networks/f5-common-python/releases/download/v{{ versions.f5sdk }}/f5-sdk-{{ versions.f5sdk }}-1.el7.noarch.rpm
    - https://github.com/F5Networks/f5-icontrol-rest-python/releases/download/v{{ versions.icontrol }}/f5-icontrol-rest-{{ versions.icontrol }}-1.el7.noarch.rpm
    - https://github.com/F5Networks/f5-openstack-agent/releases/download/v{{ versions.agent }}/f5-openstack-agent-{{ versions.agent }}-1.el7.noarch.rpm
    - https://github.com/F5Networks/f5-openstack-lbaasv2-driver/releases/download/v{{ versions.driver }}/f5-openstack-lbaasv2-driver-{{ versions.driver }}-1.el7.noarch.rpm
  when: (download_prefix | regex_search("^https://github.com")) != None

# yum uninstall is pretty slow in osp, so use rpm instead.
- name: uninstall legacy f5-* using rpm
  shell: |
    f5_rpms=`rpm -qa | grep -E "^f5-"`
    if [ -n "$f5_rpms" ]; then rpm -ev $f5_rpms; fi
  when: test_env == "osp"

- name: uninstall legacy f5-* using yum
  yum:
    name:
      - f5-openstack-agent.noarch
      - f5-openstack-lbaasv2-driver.noarch
      - f5-icontrol-rest.noarch
      - f5-sdk.noarch
    state: removed
  when: test_env != "osp"

- name: install f5-*
  shell: |
    rpm -ivh \
      f5-sdk-{{ versions.f5sdk }}-1.el7.noarch.rpm \
      f5-icontrol-rest-{{ versions.icontrol }}-1.el7.noarch.rpm \
      f5-openstack-lbaasv2-driver-{{ versions.driver }}-1.el7.noarch.rpm \
      f5-openstack-agent-{{ versions.agent }}-1.el7.noarch.rpm
  args:
    chdir: /tmp
    removes: f5-openstack-agent-{{ versions.agent }}-1.el7.noarch.rpm
    warn: False