- name: collect bigip device info
  bigip_device_info:
    gather_subset:
      # - system-info
      - partitions
      # - provision-info
      # - interfaces
      # - client-ssl-profiles
      - ltm-pools
      - virtual-servers
      # - vlans
      # - nodes
      - virtual-addresses
      # - profiles
      # - devices
      # - http-profiles
      - monitors
    provider:
      user: admin
      server: "{{ item }}"
      password: "{{ hostvars[item].admin_password }}"
      validate_certs: False
  register: bigip_infos
  with_items: "{{ groups['bigips'] }}"
  delegate_to: localhost

- name: assert resources are removed on bigips
  assert:
    that:
      # TODO: assert partition is removed.
      # - "'{{project_id}}' in '{{item.partitions | map(attribute='name') | list | join(' ') }}'"
      - "'{{loadbalancer_id}}' not in '{{item.virtual_addresses | map(attribute='name') | list | join(' ') }}'"
      - "'{{listener_id}}' not in '{{item.virtual_servers | map(attribute='name') | list | join(' ') }}'"
      - "'{{pool_id}}' not in '{{item.ltm_pools | map(attribute='name') | list | join(' ') }}'"
      - "'{{ healthmonitor_id }}' not in '{{ item.gateway_icmp_monitors | map(attribute='name') | list | join(' ') }}'"
    quiet: yes
  with_items: "{{bigip_infos.results}}"
  loop_control:
    label: "{{ item.item }}"

- name: assert members are removed on bigips
  assert:
    that:     
      - "'{{ item[0] }}' not in '{{ item[1].ltm_pools | map(attribute='members') | flatten | map(attribute='description') | list | join(' ') }}'"
    quiet: yes
  with_nested:
    - "{{ member_ids }}"
    - "{{ bigip_infos.results }}"
  loop_control:
    label: "memberid: '{{ item[0] }}'"
